name: flutterappreview
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: 1.0.1
  flutter_rounded_date_picker: 1.0.4

  cupertino_icons: ^0.1.3
  flutter_swiper: any
  intl: ^0.16.0
  scoped_model: ^1.0.1
  flutter_material_color_picker: ^1.0.5
  english_words: ^3.1.5
  redux: ^4.0.0
  flutter_redux: ^0.6.0
  material_search: ^0.2.8
  dynamic_theme: ^1.0.1
  eva_icons_flutter: ^2.0.0
  flare_flutter: ^2.0.1
  gradient_widgets: ^0.5.2
  liquid_swipe: '1.2.0'
  url_launcher: ^5.4.2
  percent_indicator: ^2.1.1+1
  http: ^0.12.0+4
  provider: 3.0.0+1
  flutter_gallery_assets: 0.1.6
  fluro: ^1.3.1
  path_provider: ^1.6.5
  share_extend: ^1.1.3
  carousel_pro: ^1.0.0
  common_utils: ^1.1.1
  device_id: any
  device_info: any
  toast: ^0.1.5
  dashed_container: ^1.0.1
  dotted_border: ^1.0.5
  random_pk: any
  flutter_signin_button: ^1.0.0
  nice_button: ^0.1.7
  slider_button: ^0.5.0
  spring_button: ^1.0.13
  pimp_my_button: ^1.0.0
  flutter_progress_button: ^1.0.0
  rounded_loading_button: ^1.0.4
  like_button: ^0.2.0
  ff_annotation_route: ^2.0.8
  popup_menu: ^1.0.5
  mobile_popup: ^1.2.0
  popup_box: ^0.1.0
  star_menu: ^1.0.4
  fab_circular_menu: ^1.0.0
  hidden_drawer_menu: ^1.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/credits/
    - assets/flare/
    - assets/icon/
    - assets/music/
    - assets/images/
    - assets/img/
    - images/
    - assets/adidas.png
    - assets/360.png
    - assets/cart.png
    - assets/sound_wave.jpg
    - assets/my_waves.jpg
    - assets/some_one_like_you.jpg
    - assets/24K_carat_magic.jpg
    - assets/sunflower.jpg
    - assets/solo_dance.jpg

  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik/Rubik-Regular.ttf
        - asset: fonts/Rubik/Rubik-Medium.ttf
        - asset: fonts/Rubik/Rubik-Bold.ttf
        - asset: fonts/Rubik/Rubik-Italic.ttf
          style: italic

    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono/RobotoMono-Regular.ttf
          weight: 400
        - asset: fonts/RobotoMono/RobotoMono-Medium.ttf
          weight: 500
        - asset: fonts/RobotoMono/RobotoMono-Bold.ttf
          weight: 800

    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand/Quicksand-Regular.ttf
          weight: 400
        - asset: fonts/Quicksand/Quicksand-Medium.ttf
          weight: 500
        - asset: fonts/Quicksand/Quicksand-Bold.ttf
          weight: 800

    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-Regular.ttf
        - asset: fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/poppins/Poppins-Medium.ttf
        - asset: fonts/poppins/Poppins-Italic.ttf
          style: italic

    - family: NotoSans
      fonts:
        - asset: fonts/NotoSans/NotoSans-Regular.ttf
        - asset: fonts/NotoSans/NotoSans-Bold.ttf

    - family: fontello
      fonts:
        - asset: fonts/fontello.ttf

    - family: Dosis
      fonts:
        - asset: fonts/Dosis/Dosis-Regular.ttf
          weight: 400
        - asset: fonts/Dosis/Dosis-Medium.ttf
          weight: 500
        - asset: fonts/Dosis/Dosis-SemiBold.ttf
          weight: 600
        - asset: fonts/Dosis/Dosis-Bold.ttf
          weight: 800
        - asset: fonts/Dosis/Dosis-ExtraBold.ttf
          weight: 900
    - family: Mali
      fonts:
        - asset: fonts/Mali-Regular.ttf